require("GenderfluidRatte.keymapping").setup()
require("GenderfluidRatte.options").setup()
require("GenderfluidRatte.lazy_plugins").setup()
require("GenderfluidRatte.language_servers")
require("GenderfluidRatte.colorscheme").setup()
